export const SAVE_CREDENTIALS = "SAVE_CREDENTIALS";
export const LOGIN_FORM_IS_VALID = "LOGIN_FORM_IS_VALID";
export const LOGIN_AUTHENTICATED = "LOGIN_AUTHENTICATED";
export const IS_REGISTERING = "IS_REGISTERING";
